import { useEffect,useRef,useState } from 'react'
import { documentApi } from '../api/documents'
import { chatApi } from '../../chat/api/chat'
import type { Document } from '../types'
import type { Conversation } from '../../chat/types'
import { useUploads } from '../store/uploads'
import { acceptedFiles } from '../utils/files'
import { explain } from '../../../shared/errors/errors'
export function DocumentPicker({conversation,onChange,onUpload,disabled}:{conversation:Conversation;onChange:(c:Conversation)=>void;onUpload:(files:File[])=>void;disabled:boolean}){
 const [documents,setDocuments]=useState<Document[]>([]);const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const [more,setMore]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const input=useRef<HTMLInputElement>(null);const alive=useRef(true)
 const jobs=useUploads(s=>s.jobs).filter(j=>j.conversationId===conversation.id);const all=conversation.document_scope==='all_owner';const ids=conversation.document_ids??[]
 const complete=jobs.filter(j=>j.stage==='ready').map(j=>j.id).join(',')
 async function list(next=0){const r=await documentApi.list(next);if(!alive.current)return;setDocuments(old=>next?[...old,...r.documents].filter((d,i,a)=>a.findIndex(x=>x.id===d.id)===i):r.documents);setOffset(next+r.documents.length);setMore(r.documents.length===50)}
 useEffect(()=>{alive.current=true;list().catch(e=>{if(alive.current)setError(explain(e))}).finally(()=>{if(alive.current)setLoading(false)});return()=>{alive.current=false}},[complete])
 const missing=ids.filter(id=>!documents.some(d=>d.id===id)).join(',')
 useEffect(()=>{if(!missing)return;let active=true;Promise.all(missing.split(',').map(id=>documentApi.status(id))).then(found=>{if(active)setDocuments(old=>[...old,...found].filter((d,i,a)=>a.findIndex(x=>x.id===d.id)===i))}).catch(e=>{if(active)setError(explain(e))});return()=>{active=false}},[missing])
 async function change(documentId?:string,useAll?:boolean){if(saving||disabled)return;setSaving(true);setError('');try{const latest=await chatApi.get(conversation.id);const selected=new Set(latest.document_ids??[]);if(documentId){if(selected.has(documentId))selected.delete(documentId);else selected.add(documentId)}const updated=await chatApi.select(conversation.id,useAll?'all_owner':'selected',useAll?[]:[...selected]);if(alive.current)onChange(updated)}catch(e){if(alive.current)setError(explain(e))}finally{if(alive.current)setSaving(false)}}
 const included=(d:Document)=>all?d.status==='ingested':ids.includes(d.id)
 const available=documents.filter(d=>!included(d)&&d.title.toLowerCase().includes(query.toLowerCase()))
 const selected=documents.filter(included)
 const pending=jobs.filter(j=>j.stage!=='ready'&&!selected.some(d=>d.id===j.documentId))
 return <div className="document-picker"><div className="row"><h2>Chat files</h2><button disabled={saving||loading} onClick={()=>list().catch(e=>setError(explain(e)))}>Refresh</button></div><button className="picker-upload" disabled={disabled||saving} onClick={()=>input.current?.click()}>＋ Upload from device</button><input hidden ref={input} type="file" multiple accept={acceptedFiles} onChange={e=>{onUpload(Array.from(e.target.files??[]));e.target.value=''}}/><label className="check"><input type="checkbox" checked={all} disabled={disabled||saving} onChange={e=>void change(undefined,e.target.checked)}/>Use all my ingested documents</label>
 {error&&<p className="error" role="alert">{error}</p>}<section className="picker-section"><h3>1 · Available documents</h3><input aria-label="Search loaded documents" placeholder="Search loaded documents…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="picker-list">{loading?<p role="status" className="muted small">Loading documents…</p>:available.length?available.map(d=><div className="picker-file" key={d.id}><div><strong>{d.title}</strong><small>{d.status}</small></div><button aria-label={'Select '+d.title} disabled={disabled||saving||d.status!=='ingested'||all} onClick={()=>void change(d.id)}>＋</button></div>):<p className="muted small">No matching unselected documents.</p>}</div>{more&&<button disabled={saving} onClick={()=>list(offset).catch(e=>setError(explain(e)))}>Load more</button>}</section>
 <section className="picker-section"><h3>2 · In this conversation</h3>{all&&<p className="muted small">All ingested documents are included, including future uploads.</p>}<div className="picker-list">{selected.map(d=><div className="picker-file" key={d.id}><div><strong>{d.title}</strong><small>Selected · ready</small></div>{!all&&<button aria-label={'Remove '+d.title+' from chat'} disabled={disabled||saving} onClick={()=>void change(d.id)}>×</button>}</div>)}{pending.map(j=><div className="picker-file" key={j.id}><div><strong>{j.name}</strong><small>{j.error||j.stage+' · will attach when ready'}</small></div></div>)}{!selected.length&&!pending.length&&<p className="muted small">Select above or upload a file to add it here.</p>}</div></section><p className="muted small">Removing a file here only removes it from this chat.</p></div>
}
