import { useEffect,useState } from 'react'
import { documentApi } from '../api/documents'
import type { Document } from '../types'
import { Modal } from '../../../shared/components/Modal'
import { explain } from '../../../shared/errors/errors'
export function ArtifactsScreen(){const [documents,setDocuments]=useState<Document[]>([]);const [more,setMore]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [selected,setSelected]=useState<Document|null>(null)
 async function load(offset=0){setLoading(true);try{const r=await documentApi.list(offset);setDocuments(old=>offset?[...old,...r.documents]:r.documents);setMore(r.documents.length===50);setError('')}catch(e){setError(explain(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 return <main className="artifacts-screen"><p className="eyebrow">YOUR LIBRARY</p><div className="row"><h1>Artifacts</h1><button disabled={loading} onClick={()=>void load()}>Refresh</button></div><p className="muted">Documents available to your conversations. Upload and select files from a chat’s + menu.</p><input className="artifact-search" aria-label="Search loaded artifacts" placeholder="Search loaded documents…" value={query} onChange={e=>setQuery(e.target.value)}/>{error&&<p className="error" role="alert">{error}</p>}<div className="artifact-grid">{documents.filter(d=>d.title.toLowerCase().includes(query.toLowerCase())).map(d=><button className="artifact-card" key={d.id} onClick={()=>setSelected(d)}><span aria-hidden="true">▤</span><strong>{d.title}</strong><small>{d.status}</small></button>)}</div>{loading&&<p role="status">Loading…</p>}{!loading&&!documents.length&&<p className="muted">No documents yet. Upload one from a chat to get started.</p>}{more&&<button disabled={loading} onClick={()=>void load(documents.length)}>Load more</button>}<Modal open={!!selected} title="Document details" onClose={()=>setSelected(null)}><h3>{selected?.title}</h3><p>Status: {selected?.status}</p><p className="muted small">Document ID: {selected?.id}</p><p>Use the file picker in a conversation to include this document in its answers.</p></Modal></main>
}
